### ISSUE TITLE
Eliminate manual route registration

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-storefront-core#138]
Currently, all storefront routes are registering through manually adding lines 
 in the extension https://github.com/VirtoCommerce/vc-storefront-core/blob/master/VirtoCommerce.Storefront/Routing/MapStorefrontRouteBuilderExtension.cs#L18
That's actions are necessary because of storefront routing has the next format /{storeId}/{locale}/ and we must to normalized each request before the routing process.
https://virtocommerce.com/docs/vc2devguide/working-with-storefront/storefront-seo-routing

Need to find out a solution to eliminate these manual route registration and use only  ASP.NET Core standard routes registration way  (Attributes or Controller and methods names)

**Comment by avas** [comment]
Vitaly added some routing tests while working on this task. I modified these tests to test actual routing and added test case for all manual routing entries. After that, I just used `StorefrontRouteAttribute` and `StorefrontApiRouteAttribute` added by Vitaly to create same routes and eliminate manual routing setup.

**Comment by avas** [comment]
After transition to attribute-based routing dynamic slug routes stopped working. This problem is caused by the fact that ASP.NET Core MVC uses 2 different routers:
* `AttributeRoute` that handles attribute-based routes (executes before `SlugRoute`);
* `MvcRouteHandler` that handles manually registered routes (acts as handler for `Route` and executes right after `SlugRoute.OnRouteMatched`).

Usually MVC route contains some specific implementation of `IRouter` that attempts to find matching action and, if succeeded, sets request handler by assigning value to `RouteContext.Handler`.  `SlugRoute` is derived from `Route` and uses `MvcRouteHandler` for that purpose, but it doesn't set `Handler` explicitly - instead, it just gives some hints to `MvcRouteHandler` by filling controller name, action name and request parameters to `RouteContext.RouteData.Values`. Previously, when routes were registered manually, `MvcRouteHandler` handled all controller actions, so it was correctly getting controller action by those hints. But now, after transition to attribute-based routing, all actions are handled by `AttributeRoute`, and `MvcRouteHandler` handles nothing. That's why it couldn't resolve controller action, and for dynamic routes storefront was returning 404.

So, to solve this problem, I modified `SlugRoute`. Now it attempts to find matching controller action itself and, if succeeded, assigns `RouteContext.Handler` that invokes that action. This way dynamic slug routes appear to work correctly.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.5
