### ISSUE TITLE
Note to the seller doesn't get through

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-storefront-core#180]
When a customer writes something in the field Note to seller (within the Cart) that information doesn't get through. It is not in the order, it is not in any email template, it doesn't exist in Comments in Platform (the box says "no comments") and I also wasn't able to find it anywhere in the database.

UPDATE
That's the "note": "Special instructions for seller" field I was talking about.

**Comment by tatarincev** [comment]
How to repeat:
Electronics theme
1. Add some product to cart
2. Open cart detail
3. Type something in the text area in "Special instructions for seller"
4. Click checkout (comment will be added to cart only when user click on this button)
5. Open cart detail again (note textarea  will be empty) 
**Expected behavior:** a note must be there

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/v3.2.7
