### ISSUE TITLE
Users are reporting intermittently receiving an empty shopping cart after they've added product to their cart

### ISSUE THREAD

**Issue by emathavan** [VirtoCommerce/vc-storefront-core#261]
Users are reporting intermittently receiving an empty shopping cart after they've added product to their cart.  It doesn't seem to matter if the user is logged in or a guest.  This can happen when loading the shopping cart page or during checkout.

Version info: 
- Browser version: All versions
- Platform version: 2.13.21
- Storefront version: 1.0

Production configuration:  3 Frontend/Storefront web tiers, 1sql db, redis distributed cache

### Expected behavior
When user adds an item to the cart it should be there

### Steps to reproduce
We are unable to reproduce as this only happens on Production

**Comment by yecli** [comment]
In [storefront v3.2.9](https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.9) we fixed the bug with simultaneous cart updates:

- Fixed the bug with transient cart invalidation in cache. Before the fix all who used temporary cart shared single cached instance because of empty Id property.

[Commit](https://github.com/VirtoCommerce/vc-storefront-core/commit/477158985368ff5326703e018b2eb203ff591145)

Seems problems you described could be caused by this.
Try to update to the latest storefront version.

**Comment by emathavan** [comment]
Andrey, I see that Virto Commerce is now on the ASP.NET Core framework.  Do you still provide support for old legacy framework?

**Comment by yecli** [comment]
Yes, we will continue to support platform v.2. New features will appear in v.3 (NET Core).
