### ISSUE TITLE
Unit tests fail

### ISSUE THREAD

**Issue by krankenbro** [VirtoCommerce/vc-storefront-core#339]
On the CI server Unit Tests run:
dotnet vstest "VirtoCommerce.Storefront.Tests\bin\Debug\netcoreapp2.2\VirtoCommerce.Storefront.Tests.dll"  /TestCaseFilter:(Category=Unit|Category=CI)
And we get: 
![image](https://user-images.githubusercontent.com/42555001/68574749-44c91380-0473-11ea-99fd-fdda7a0c025d.png)
[Full log](https://ci.virtocommerce.com/job/VirtoCommerce/job/vc-storefront-core/job/dev/41/console)

**Comment by tatarincev** [comment]
The CI build server runs unit tests that only tagged by [Category=Unit or CI] and these tests that you successfully fixed were intended to demonstrate true fail scenarios and excluded from CI.
The issue was fixed by this commit https://github.com/VirtoCommerce/vc-storefront-core/commit/eb433b4c4fccc50f4bebd21f1dbc4bdeb3d6573c
